# Generated by Django 5.1.3 on 2025-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataayamhistory',
            name='jumlah_ayam',
        ),
        migrations.RemoveField(
            model_name='dataayamhistory',
            name='jumlah_ayam_awal',
        ),
        migrations.RemoveField(
            model_name='dataayamhistory',
            name='mortalitas',
        ),
        migrations.RemoveField(
            model_name='dataayamhistory',
            name='tanggal_mulai',
        ),
        migrations.RemoveField(
            model_name='dataayamhistory',
            name='tanggal_panen',
        ),
        migrations.RemoveField(
            model_name='dataayamhistory',
            name='usia_ayam',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staf', 'Staf'), ('pemilik', 'Pemilik'), ('Alat', 'alat')], default='staf', max_length=10),
        ),
    ]
