# Generated by Django 5.1.3 on 2025-02-28 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_dataayamhistory_jumlah_ayam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataayamhistory',
            name='jumlah_ayam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataayamhistory',
            name='jumlah_ayam_awal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataayamhistory',
            name='mortalitas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataayamhistory',
            name='tanggal_mulai',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dataayamhistory',
            name='tanggal_panen',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dataayamhistory',
            name='usia_ayam',
            field=models.IntegerField(default=0),
        ),
    ]
