# Generated by Django 5.1.3 on 2024-11-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chickendata'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumlahAyam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_ayam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mortalitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortalitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsiaAyam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usia_ayam', models.IntegerField()),
            ],
        ),
    ]
