# Generated by Django 5.1.3 on 2025-02-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dataayamhistory_jumlah_ayam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataayamhistory',
            name='jumlah_ayam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dataayamhistory',
            name='jumlah_ayam_awal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dataayamhistory',
            name='mortalitas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataayamhistory',
            name='tanggal_mulai',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dataayamhistory',
            name='tanggal_panen',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dataayamhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dataayamhistory',
            name='usia_ayam',
            field=models.IntegerField(),
        ),
    ]
