# Generated by Django 5.1.3 on 2024-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jumlahayam_mortalitas_usiaayam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_ayam_awal', models.IntegerField()),
                ('tanggal_panen', models.DateField()),
                ('jumlah_ayam', models.IntegerField()),
                ('mortalitas', models.FloatField()),
                ('usia_ayam', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataAyam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_ayam_awal', models.IntegerField()),
                ('tanggal_panen', models.DateField()),
                ('jumlah_ayam', models.IntegerField()),
                ('mortalitas', models.FloatField()),
                ('usia_ayam', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ChickenData',
        ),
        migrations.DeleteModel(
            name='JumlahAyam',
        ),
        migrations.DeleteModel(
            name='Mortalitas',
        ),
        migrations.DeleteModel(
            name='UsiaAyam',
        ),
    ]
