# Generated by Django 5.1.3 on 2024-11-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chickenfarm_dataayam_delete_chickendata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChickenFarm',
        ),
    ]
