# Generated by Django 5.1.3 on 2025-02-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dataayamhistory_jumlah_ayam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataayamhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
