# Generated by Django 5.1.3 on 2025-03-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dataayamhistory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alat_id', models.CharField(max_length=255, unique=True)),
                ('battery_level', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, 'Aktif'), (1, 'Nonaktif')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staf', 'Staf'), ('pemilik', 'Pemilik'), ('alat', 'Alat')], default='staf', max_length=10),
        ),
    ]
