# Generated by Django 5.1.3 on 2025-03-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alat_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='floor',
            field=models.IntegerField(choices=[(1, 'first floor'), (2, 'second floor')], default=1),
        ),
    ]
