# Generated by Django 5.1.3 on 2024-11-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dataayam_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAyamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_ayam_awal', models.IntegerField()),
                ('tanggal_panen', models.DateField()),
                ('jumlah_ayam', models.IntegerField()),
                ('mortalitas', models.FloatField()),
                ('usia_ayam', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_ayam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.dataayam')),
            ],
        ),
    ]
