# Generated by Django 5.1.3 on 2024-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dataayamhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartFarming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_ayam', models.IntegerField()),
                ('target_tanggal', models.DateField()),
                ('tanggal_mulai', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
