# Generated by Django 5.1.3 on 2025-04-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='api_key',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alat',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nonaktif'), (1, 'Aktif')], default=0),
        ),
    ]
