# Generated by Django 5.1.3 on 2024-11-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_parameter_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartFarming',
        ),
    ]
