# Generated by Django 5.1.3 on 2025-04-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alat_api_key_alter_alat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
