# Generated by Django 5.1.3 on 2024-11-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_startfarming'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
