# Generated by Django 5.1.3 on 2025-04-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staf', 'Staf'), ('pemilik', 'Pemilik'), ('tamu', 'Tamu')], default='staf', max_length=10),
        ),
    ]
