# Generated by Django 5.1.3 on 2025-04-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_customuser_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
