# Generated by Django 5.1.3 on 2025-04-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alat',
            name='status',
        ),
    ]
