# Generated by Django 5.1.3 on 2025-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_alat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='floor',
            field=models.IntegerField(choices=[(1, 'Lantai 1'), (2, 'Lantai 2')], default=1),
        ),
    ]
