# Generated by Django 5.1.3 on 2025-05-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_parameter_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alat',
            name='battery_level',
        ),
    ]
